name: denoising
channels:
  - cjj3779
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu=1.4.0=py36h6bf4e57_0
  - attrs=18.2.0=py_0
  - audioread=2.1.5=py36_0
  - backcall=0.1.0=py_0
  - blas=1.1=openblas
  - bleach=1.5.0=py36_0
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.10.15=ha4d7672_0
  - certifi=2018.10.15=py36_1000
  - click=7.0=py_0
  - cycler=0.10.0=py_1
  - dbus=1.13.0=h3a4f0e9_0
  - decorator=4.3.0=py_0
  - entrypoints=0.2.3=py36_1002
  - expat=2.2.5=hfc679d8_2
  - ffmpeg=2.8.6=hf82bc7d_7
  - fontconfig=2.13.1=h65d0f4c_0
  - freetype=2.9.1=h6debe1e_4
  - gettext=0.19.8.1=h5e8e0c9_1
  - glib=2.56.2=h464dc38_1
  - gmp=6.1.2=hfc679d8_0
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.5=h5856ed1_0
  - h5py=2.8.0=py36h097b052_4
  - hdf5=1.10.3=hc401514_2
  - html5lib=0.9999999=py36_0
  - icu=58.2=hfc679d8_0
  - ipykernel=5.1.0=pyh24bf2e0_0
  - ipython=7.1.1=py36h24bf2e0_1000
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.1=py36_1000
  - jinja2=2.10=py_1
  - joblib=0.13.0=py_0
  - jpeg=9c=h470a237_1
  - jsonschema=3.0.0a3=py36_1000
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36h2d50403_2
  - libffi=3.2.1=hfc679d8_5
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libiconv=1.15=h470a237_3
  - libpng=1.6.35=ha92aebf_2
  - libprotobuf=3.6.1=hd28b015_0
  - librosa=0.6.2=py_0
  - libsodium=1.0.16=h470a237_1
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - llvmlite=0.25.0=py36hd28b015_1
  - markdown=2.6.11=py_0
  - markupsafe=1.1.0=py36h470a237_0
  - matplotlib=3.0.1=h8a2030e_1
  - matplotlib-base=3.0.1=py36hc039c98_1
  - mistune=0.8.4=py36h470a237_0
  - nbconvert=5.3.1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hfc679d8_1
  - notebook=5.7.0=py36_1000
  - numba=0.40.0=py36hf8a1672_0
  - numpy=1.15.4=py36_blas_openblashb06ca3d_0
  - openblas=0.3.3=ha44fe06_1
  - openssl=1.0.2p=h470a237_1
  - pandas=0.23.4=py36hf8a1672_0
  - pandoc=2.3.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pcre=8.41=hfc679d8_3
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pip=19.0.3=py36_0
  - prometheus_client=0.4.2=py_0
  - prompt_toolkit=2.0.7=py_0
  - protobuf=3.6.1=py36hfc679d8_1
  - pthread-stubs=0.4=h470a237_1
  - ptyprocess=0.6.0=py36_1000
  - pyflame=1.5.2=py36hfc679d8_0
  - pygments=2.2.0=py_1
  - pyparsing=2.3.0=py_0
  - pyqt=5.6.0=py36h8210e8a_7
  - pyrsistent=0.14.5=py36h470a237_1
  - python=3.6.6=h5001a0f_3
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - pyyaml=3.13=py36h470a237_1
  - pyzmq=17.1.2=py36hae99301_1
  - qt=5.6.2=hf70d934_9
  - qtconsole=4.4.2=py_1
  - readline=7.0=haf1bffa_1
  - resampy=0.2.1=py_1
  - scikit-learn=0.20.0=py36_blas_openblash00c3548_201
  - scipy=1.1.0=py36_blas_openblashb06ca3d_202
  - send2trash=1.5.0=py_0
  - setuptools=40.5.0=py36_0
  - sip=4.18.1=py36hfc679d8_0
  - six=1.11.0=py36_1001
  - sqlite=3.25.3=hb1c47c0_0
  - terminado=0.8.1=py36_1001
  - testpath=0.4.2=py36_1000
  - tk=8.6.8=ha92aebf_0
  - tornado=5.1.1=py36h470a237_0
  - tqdm=4.31.1=py_0
  - traitlets=4.3.2=py36_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.14.1=py_0
  - wheel=0.32.2=py36_0
  - widgetsnbextension=3.4.2=py36_1000
  - x264=1!152.20180717=h470a237_1
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xz=5.2.4=h470a237_1
  - yaml=0.1.7=h470a237_1
  - zeromq=4.2.5=hfc679d8_6
  - zlib=1.2.11=h470a237_3
  - keras-gpu=2.0.8=py36h0585f72_0
  - tensorflow-tensorboard=0.4.0=py36hf484d3e_0
  - pip:
    - enum34==1.1.6
    - future==0.17.1
    - keras==2.0.8
    - keras-tcn==2.6.7
    - mir-eval==0.5
    - pystoi==0.2.1
prefix: /home/rmicci18/miniconda3/envs/denoising